### ISSUE TITLE
Automating the --account_flag during compilation

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/nile#102]
When running `nile compile`, there should be a standardized way to let the compiler know that a contract is an account and thus automatically insert the `--account_contract` flag. My initial strategy was to simply look for `Account` in the contract name, but after the discussion in #79, this appears to be too restrictive. A better approach might be to trigger the flag when `Account` is the suffix i.e. `Account.cairo` and `<something>Account.cairo`.

**Comment by JulissaDantes** [comment]
Idea: we can make something to identify accounts contracts even if the name is not account, like we do `%lang starknet` , we would do `%type account ` or something similar.
