### ISSUE TITLE
Running nile setup throws NameError

### ISSUE THREAD

**Issue by tserg** [OpenZeppelin/nile#111]
Nile version: 0.6.1 / 0.6.1.post1.dev1+g072b05e
Python version: 3.7.9
OS: Ubuntu 20.04
Using miniconda for env

Running `nile setup KEY` throws the following error. The error is probably not with the KEY (I have set it in `.env`, and also tried setting in console). The same error is thrown when installing via `pip` or when building the development version.
```
File "/home/user/miniconda3/envs/nile/lib/python3.7/site-packages/nile/core/account.py", line 23, in __init__
    self.signer = Signer(int(os.environ[signer]))
NameError: name 'Signer' is not defined
```

**Comment by andrew-fleming** [comment]
Hey, @tserg. Thank you for posting this! After installation, have you initialized Nile with `nile init`?

**Comment by tserg** [comment]
Yes, just retried on a fresh directory.

**Comment by andrew-fleming** [comment]
> Yes, just retried on a fresh directory.

Have you tried with a fresh venv?

If so, can you walk me through how you set up your venv? And also to confirm, you're getting the `NameError` for `Signer` upon Nile's installation through pip, correct? Like `pip install cairo-nile` => error?

**Comment by tserg** [comment]
I was getting the `NameError` for `Signer` only when running `nile setup`.

I just tried a fresh install with these steps (also tried with venv)
1. `conda create --name ENV_NAME python==3.7.9`
2. `conda activate ENV_NAME`
3. `pip install nile-cairo`
4. In a new directory, `nile init`
5. `echo KEY=1234 > .env` (but it is not detected so I ran `export KEY=1234`
6. `nile setup KEY`

Now, it is returning this error:
```
Got InvalidURL while trying to access /gateway/add_transaction.
...
subprocess.CalledProcessError: Command '['starknet', 'deploy', '--contract', '/home/user/miniconda3/envs/nile-test/lib/python3.7/site-packages/nile/artifacts/Account.json', '--inputs', '883045738439352841478194533192765345509759306772397516907181243450667673002', '--gateway_url=None']' returned non-zero exit status 1.
```

**Comment by andrew-fleming** [comment]
Ah one thing that appears to be missing in your setup is starting the Nile node for the local network. Before number 6 in your setup, run `nile node` and in a separate terminal, cd to the Nile root and run `nile setup KEY` there

**Comment by tserg** [comment]
I retried the steps on a new machine and it is working now. Thanks for the help! Closing this issue.

**Comment by RayXpub** [comment]
Also having the same issue, tried all the above steps along with creating a new venv from scratch but still getting : `NameError: name 'Signer' is not defined` error.
