### ISSUE TITLE
Fix or document Nile plugin parameter style

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/nile#115]
As @franalgaba said in #113:

> Also, I identified an issue while using arguments and options in commands through the NRE. To pass arguments and options from a command, it is needed to follow click guidelines. These guidelines specify that should be passed as a list of items in string format:
> 
> ```python
> # Decorate the method that will be the command name with `click.command`
> @click.command()
> @click.argument("a", type=int)
> @click.argument("b", type=int)
> # You can define custom parameters as defined in `click`: https://click.palletsprojects.com/en/7.x/options/
> def greet(a, b):
>     # Help message to show with the command
>     """
>     Subcommand plugin that does something.
>     """
>     # Done! Now implement your custom functionality in the command
>     click.echo("Hello! I'm a Nile plugin")
>     return a + b
> ```
> For example, to use it with the NRE:
> 
> ```python
> from nile.nre import NileRuntimeEnvironment
> 
> nre = NileRuntimeEnvironment()
> ret = nre.greet(["1", "2"])
> # ret is equal to 3
> ```

Either implement a workaround to make passing arguments happier, or document it.

**Comment by martriay** [comment]
Probably deconstructing `*args` in

https://github.com/OpenZeppelin/nile/blob/main/src/nile/core/plugins.py#L23

**Comment by martriay** [comment]
Maybe @franalgaba wants to tackle another one 👀

**Comment by ericnordelo** [comment]
@martriay Having built the nile-coverage plugin recently, I think that not all the entry points defined in the plugin should be available to the NRE (that's the current behavior). I think it would be a better approach to separate the entry points for CLI from the ones for NRE (one method from the plugin could be used in both, but that's for the plugin to define). 

Passing click commands to the NRE is a bad design, in my opinion. 

Implementing this is pretty straightforward, but we need to document the behavior in the HOW TO CREATE A PLUGIN guide we have.

**Comment by martriay** [comment]
I think I agree. it made sense back then with the minimal initial functionality but now it may be worth separating them.
