### ISSUE TITLE
Namespace cannot be imported when trying to so from openzeppelin

### ISSUE THREAD

**Issue by ametel01** [OpenZeppelin/nile#123]
Imports works when importing from local

**Comment by andrew-fleming** [comment]
Hey, @ametel01. It's a little unclear to me what the issue is exactly. Could you provide some more details? Are you trying to import a namespace from the OpenZeppelin contracts package?

**Comment by ametel01** [comment]
Individual functions can be imported from OZ contracts packages but not namespaces. So this: 
```from openzeppelin.introspection.ERC165 import ERC165```

won't work.

**Comment by andrew-fleming** [comment]
Ahhh yes, you are correct. The namespace feature hasn't been officially released yet, but we're working to ship that out soon :)

**Comment by martriay** [comment]
@ametel01 this was released on https://github.com/OpenZeppelin/cairo-contracts/releases/tag/v0.2.0.
