### ISSUE TITLE
make test results in python error

### ISSUE THREAD

**Issue by kevindarby** [OpenZeppelin/nile#125]
After nile init, main branch

File "/usr/local/lib/python3.7/site-packages/pytest_cairo/plugin.py", line 8, in <module>
    from pytest import Collector, Config, Parser, PytestPluginManager, StashKey
ImportError: cannot import name 'Config' from 'pytest' (/usr/local/lib/python3.7/site-packages/pytest/__init__.py)

**Comment by andrew-fleming** [comment]
Hey, @kevindarby. Unfortunately, I haven't been able to reproduce this error. Could you provide some more details?
