### ISSUE TITLE
test nile commands

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/nile#13]
it'd be nice to implement some basic testing, probably starting with `compile` and `clean`.
this would make reviews and releases much more easy.

**Comment by TimNooren** [comment]
Hi @martriay, I'd love to contribute here. Would https://github.com/OpenZeppelin/nile/compare/main...TimNooren:add_tests?expand=1 be up to standard? If so I'd be happy to open a PR:)

**Comment by martriay** [comment]
Yes! Please do :)
