### ISSUE TITLE
Got ClientConnectorCertificateError while trying to access https://alpha4.starknet.io/gateway/add_transaction.

### ISSUE THREAD

**Issue by qkaver** [OpenZeppelin/nile#133]
localhost can work, but goerli can not work
` --network localhost
🚀 Deploying ERC721
⏳ ️Deployment of ERC721 successfully sent at 0x0632bcc92835bb37b71c82fee273c966d0863134e4f1e2c2184dc8cb4713a7a1
🧾 Transaction hash: 0x17275a2d05f67778c1f0434b6b1b21e7a5d893c6904a10e6da50e779e819954
📦 Registering 0x0632bcc92835bb37b71c82fee273c966d0863134e4f1e2c2184dc8cb4713a7a1 in 127.0.0.1.deployments.txt
(env) (base) qinjiahaodeMacBook-Pro:starknet qkaver$ nile deploy ERC721 6001127147006152263 21336 2689760648704244976701818254133193310968075258309729491871695171359883455256 --network goerli
🚀 Deploying ERC721
Got ClientConnectorCertificateError while trying to access https://alpha4.starknet.io/gateway/add_transaction.`

**Comment by martriay** [comment]
Hello, could you provide reproduction steps? What Contracts, Nile, Cairo, etc versions are you using, and how can we reproduce this error. Thanks!
