### ISSUE TITLE
Account.cairo requires `--account_contract` flag

### ISSUE THREAD

**Issue by ericDeCourcy** [OpenZeppelin/nile#141]
Based on instructions this should not require the `--account_contract` flag, but compilation will fail stating that the flag is required. This also means that you can't compile OZ cairo contracts in their entirety

Cairo version 0.6.1
Ubuntu 20.04.2 LTS

**Comment by ericDeCourcy** [comment]
#112 seems related

**Comment by martriay** [comment]
This was fixed by #112, just not yet released.
