### ISSUE TITLE
Command  failure 

### ISSUE THREAD

**Issue by DecentrilizedMan** [OpenZeppelin/nile#146]
The following command fails for me : 
```
pip install cairo-nile
```

The output log as : 
```
ERROR: Could not find a version that satisfies the requirement cairo-nile (from versions: none)
ERROR: No matching distribution found for cairo-nile
```

**Comment by DecentrilizedMan** [comment]
python 3.8.9 , I've manually download the file and do ```python setup install ``` with it .

**Comment by JulissaDantes** [comment]
Are you by chance using a virtual environment? Sometimes their inner python version is different

**Comment by DecentrilizedMan** [comment]
Yeah , i use python virtual environment , and re-instantiated for a newer
version to get it solved .

JulissaDantes ***@***.***> 于2022年7月15日周五 21:27写道：
