### ISSUE TITLE
DOC: Update CONTRIBUTING guide to describe project setup

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/nile#172]
This is a documentation related issue. I think it would be great to have the steps for setting up the project before contributing:

Ex: Should dependencies be installed through `pip install .` or `python3 setup.py develop`. Tox must be installed manually after this? Etc...

**Comment by martriay** [comment]
you mean moving [this](https://github.com/OpenZeppelin/nile#hacking-on-nile) to CONTRIBUTING

**Comment by ericnordelo** [comment]
Kind of, but for example after running `pip install .` I still don't have `tox` installed. If the user is expected to install some dependencies manually maybe the doc should address this, or we could add all the dependencies on the setup.py (and also move that to contributing, yes).
