### ISSUE TITLE
Refactor README.md.

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/nile#199]
Fix inconsistencies like:

- Sentences ending in dot and others not.
- Inconsistencies in the persona used in sentences (Use vs. Uses).
- sh entries (optional and required params format).
- ...

Also, fix content like the order of the commands.

Improve the README organization and presentation in general.

**Comment by andrew-fleming** [comment]
I suggest we make this a total revamping of the README and add optional parameter descriptions. It'd probably be wise to add `help=` to all Click options in the CLI as well.

**Comment by ericnordelo** [comment]
Fixed in #298
