### ISSUE TITLE
Boostrap contract code is not in cairv0.10

### ISSUE THREAD

**Issue by 0xAurelou** [OpenZeppelin/nile#201]
# How to reproduce
```shell
nile init && nile compile
 ```
![image](https://user-images.githubusercontent.com/63618058/191605129-f663be77-ea6c-4462-b639-4727ddbe70da.png)

# The actual code
![image](https://user-images.githubusercontent.com/63618058/191605540-f73c3f44-cd62-4d6e-a6a0-8d6fcea2cf61.png)

# How he should be 
(I know we can migrate but it's annoying to migrate all the time)
![image](https://user-images.githubusercontent.com/63618058/191605970-2c5cd77f-12b0-43a7-8fd0-dffca63cbf2a.png)

**Comment by martriay** [comment]
what version are you using?

```sh
$ nile version
0.9.0
```

**Comment by 0xAurelou** [comment]
![image](https://user-images.githubusercontent.com/63618058/191611444-4e66d033-f988-4f3a-9d75-19762d5d67a8.png)

**Comment by martriay** [comment]
that's very weird. i guess there's some cache somewhere, can you try with reinstalling with pip's `--no-cache-dir` flag?

the reason i'm asking is because i cannot reproduce it:

![Uploading image.png…]()

**Comment by 0xAurelou** [comment]
Hi, I am really sorry it was a cache problem, I feel so dumb :pensive:  :broken_heart: 
Sorry, If I took your time sir
