### ISSUE TITLE
Improve how `declare` handles an existing class hash

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/nile#205]
When I call `declare` on an implementation contract to be used with a proxy, if it was previously declared, `register_class_hash` currently raises an exception containing the hash in the message string.  

To improve usability, I want a way to get the existing declaration's class hash (without having to parse the error message) so that it can be used afterwards.

Consider one of the following:
~~1. Use a custom error that contains the hash in a field, so that the caller of `declare` can catch the error and retrieve the hash
2. In `declare`, suppress the error if a class hash already exists, and just proceed to return with the existing class hash
3. In `declare`, suppress the error if a class hash already exists, and update the entry in the declaration file (e.g. if a different alias is provided)
4. In `declare`, have an optional flag such as `update` which allows it to do (3) only if the flag is set.~~
5. Provide a function similar to `get_declaration`, but takes a contract (rather than an alias) and returns the corresponding class hash.

**Comment by ericglau** [comment]
Alternatively, should `declare` suppress the error if a class hash already exists, and/or should it simply update the entry (e.g. if a different alias is provided)?

**Comment by ericglau** [comment]
I prefer option (4) above, since an `update` flag would make `deploy` easier to use in this scenario, and still retain the original error if an update is not desired.

**Comment by martriay** [comment]
the equivalent of (5) would be:

```python
from starkware.crypto.signature.fast_pedersen_hash import pedersen_hash
from starkware.starknet.core.os.class_hash import compute_class_hash

def get_hash(contract_class):
    return compute_class_hash(
        contract_class=contract_class,
        hash_func=pedersen_hash
    )
```
