### ISSUE TITLE
add CONTRIBUTING.md

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/nile#21]
We should base it in OpenZeppelin Cairo Contracts's [CONTRIBUTING](https://github.com/OpenZeppelin/cairo-contracts/blob/main/CONTRIBUTING.md)

**Comment by HoneyCivik** [comment]
https://github.com/OpenZeppelin/nile/issues/21#issue-1025581705

**Comment by martriay** [comment]
> Maybe adding `.pylintrc` and `.vscode/settings.json` would be a thing

Can you? 🥺
