### ISSUE TITLE
Document hex/int pattern

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/nile#216]
Here's the gist of the pattern (from @ericnordelo):
- using only `int` internally
- convert the input to `int`(from config files, starknet cli, etc..) with the `normalize_number` method
- convert to `hex` before writing to files (like in address for accounts)

**Comment by ericnordelo** [comment]
Thank you Andrew! An update trying to be more specific:

- **_Accepting and using only `integers` for Internal APIs_** (for hashes, keys, and addresses). Internal API vs. Public API needs to be better defined for this context. For example, the `send` method in the Account abstraction is used from scripts (nre) to send transactions through accounts but is also used internally, should accept hex strings or not?
- **_Accept both `hex` and `int` from external input or Public APIs_** (from config files, starknet cli output, etc..), and convert the input to int before using it internally (nile.utils.normalize_number).
- **_Convert to `hex` before writing to files_** (like in address for accounts, or class_hash for declares) to keep consistency.
- **_Convert to `hex` when is required for integrations_** (like starknet cli), right before where is needed.
