### ISSUE TITLE
Add more context to comment

### ISSUE THREAD

**Issue by ericnordelo** [OpenZeppelin/nile#219]
i actually think this comment is a bit confusing with no other context

_Originally posted by @martriay in https://github.com/OpenZeppelin/nile/pull/218#discussion_r986049902_

**Comment by martriay** [comment]
i was actually vouching for removing it haha. Wasn't the comment a clarification on the diff, rather than a clarification on the code?

**Comment by ericnordelo** [comment]
My intention with the comment was to add some clarification to the fact that other functions using `address_or_alias` normalize the number if it is not an alias, but `send` specifically doesn't. This is a difference in the code I think it could have been confusing. I'm inclined to let the comment because of this, refactoring it to something more informative, like the following idea:

"address_or_alias is not normalized first here, because Account.send is part of the nile public API, consequently accepting address as hex too"
