### ISSUE TITLE
Improve `Account.send` return format

### ISSUE THREAD

**Issue by ericglau** [OpenZeppelin/nile#222]
`Account.send` (when called from a script) currently returns a string literally like the following:
```
Invoke transaction was sent.
Contract address: 0x0002baa99045493ae32f220712fcbebd7319b45013b2f0863d8f02c3af5d29dc
Transaction hash: 0x608e0d8880123eacbb62aeab8ed765d42d19186b5dfc220f54827c6f8f40056
```

If consuming this result in a Nile script, the user needs to parse this string to determine the transaction hash.

Instead, return a result that is more programmatically consumable, for example return only the transaction hash itself, or an actual object with fields.

**Comment by ericnordelo** [comment]
The format has been improved as part of #320.
