### ISSUE TITLE
Create list of Nile plugins

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/nile#237]
- [ ] nile verifier
- [ ] coverage
- [ ] upgrades
- [ ] ???

**Comment by ericnordelo** [comment]
Can we consider this fixed having https://docs.openzeppelin.com/nile/0.12.0/plugins ?

**Comment by martriay** [comment]
yes, although i'm not sure listing plugins by OZ employees as "community plugins". it's weird.
