### ISSUE TITLE
auto calculate max_fee

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/nile#284]
instead of `0` as the default `max_fee`, nile should estimate the required fee for the users, which today have to guess it.

**Comment by ericnordelo** [comment]
I think it could make sense to wait for #320 before adding this (and I think it will be easier to add too). 

320 adds an `estimate_fee` abstraction for all the transactions, that can be used for this (I think that addressing this without that could cause a lot of unnecessary conflicts in code and tests).

IMO it can still be part of the same milestone, as long as we merge #320 first.

**Comment by andrew-fleming** [comment]
Haha yeah, I stopped my progress after adding the implementation with `account.send` because of this. I'll checkout and work over the `#320` PR. Thanks for the heads up, sir!
