### ISSUE TITLE
Support scripting

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/nile#29]
Expose a programatic API to execute `invoke`, `call` and `deploy` commands on any pre-configured network (local or mainnet by default), leveraging with the deployments management and eventually also [signers](https://github.com/OpenZeppelin/nile/issues/28).

**Comment by fracek** [comment]
Should scripting be in Python (so nile exposes a Python API) or from a shell script?

**Comment by martriay** [comment]
I think exposing python makes sense as of now, specially when you're already installing cairo and nile through pip.

**Comment by l-henri** [comment]
Hello!
This looks like something I need. I'd like to write scripts similar to migrations in truffle, but in Nile.
How can I help?

**Comment by martriay** [comment]
That's indeed the idea! Well I guess the first step would be to expose that functionality internally (`invoke`, `call`, `deploy`, etc) and then make the CLI commands depend on that "base" functionality. Once we have that, it should be automatically exportable and then we can modify the packaging system to include a programatic `nile` or `nile-lib` module :)_

**Comment by l-henri** [comment]
Hello! Here are some things I would find very useful.
- Being able to send transactions through an account contract
- Being able to use an account contract both in Nile and argent X
- Pass hexadecimal values without having to convert to decimals
- Interact with new, as well as existing contracts
- Querying tx_status in the CLI to check wether a transaction passed or not

Super excited to be able to use this 😄
