### ISSUE TITLE
No ability to pass constructor arguments

### ISSUE THREAD

**Issue by ponderingdemocritus** [OpenZeppelin/nile#30]
Currently, there is no way to pass constructor arguments in the deploy function.

This stops the ability to deploy contracts that require args in their constructors. 

Could this please be added?

**Comment by martriay** [comment]
Yes! This is in the works already thanks for raising it.

**Comment by ponderingdemocritus** [comment]
amazing! looking forward to it

**Comment by martriay** [comment]
Released in [0.2.1](https://github.com/OpenZeppelin/nile/releases/tag/v0.2.1)
