### ISSUE TITLE
Registering duplicate deployment address will delete deployment from json

### ISSUE THREAD

**Issue by andrew-fleming** [OpenZeppelin/nile#322]
The StarkNet network will correctly reject an attempted deployment of a duplicate contract address. `account.deploy` unregisters deployments upon tx rejections; therefore, if `account.deploy` rejects a duplicate deployment, it will unregister the successful deployment as well. This occurs because the `to_delete` variable looks for the address or class hash of the entry.

A potential fix might include checking if the address or class hash already exists in `register`. Currently, it only checks for duplicate aliases. See https://github.com/OpenZeppelin/nile/blob/main/src/nile/deployments.py#L13-L15

Another idea might consist of waiting for the tx status before registering contracts.

Maybe both?

**Comment by ericnordelo** [comment]
This is solved as part of #320

**Comment by ericnordelo** [comment]
Fixed in #320
