### ISSUE TITLE
nile setup failed

### ISSUE THREAD

**Issue by cafe6876** [OpenZeppelin/nile#326]
after execute next command:
 nile setup PK1 --salt 123 --max_fee 1000000000000000  --network goerli

(PK1=2161437489134303720475568176588606615766177447388189442722777539715262361321)
the privateKey is export from wallet

display error msg:
Deploying Account
⏳ ️Deployment of Account successfully sent at 0x003a34ed79a308296a9f68270a8e33c7362367952b211451c9d8781a953e7897
🧾 Transaction hash: 0x7adaf47df32e94ffae8f51cbd9688762439a26b36114d0c9bb70f6e24c7745a
📦 Registering 0x003a34ed79a308296a9f68270a8e33c7362367952b211451c9d8781a953e7897 in goerli.deployments.txt
⏳ Querying the network for transaction status...
🕒 Transaction status: RECEIVED. Trying again in 30 seconds...
❌ Transaction status: REJECTED
🛑 The transaction was rejected but no contract data is locally available to improve the error message.
🧾 Error message:
(500, {'code': <StarknetErrorCode.TRANSACTION_FAILED: 44>, 'message': 'Error at pc=0:104:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:1678)\nUnknown location (pc=0:1664)\n\nError in the called contract (0x49d36570d4e46f48e99674bd3fcc84644ddd6b96f7c741b1562b82f9e004dc7):\nError at pc=0:9:\nGot an exception while executing a hint.\nCairo traceback (most recent call last):\nUnknown location (pc=0:1351)\nUnknown location (pc=0:1328)\nUnknown location (pc=0:915)\n\nTraceback (most recent call last):\n  File "<hint1>", line 3, in <module>\nAssertionError: assert_not_zero failed: 0 = 0.'})

do you help me  to find where is the error?

**Comment by martriay** [comment]
This is related to https://github.com/OpenZeppelin/nile/issues/308, for which we'll be releasing a fix soon (it's already merged).

This error occurs when the transaction fails and Nile fails to handle the response.
