### ISSUE TITLE
Can't run nile node in macOS

### ISSUE THREAD

**Issue by kanishkatn** [OpenZeppelin/nile#35]
Hi, 

I'm on macOS Big Sur, and there is some system process running at port 5000. Cause of which, `nile node` fails to run. 

Is there a way to specify the port in `nile node` ?

**Comment by fracek** [comment]
At the moment it's not possible to change the host or port, we should do that.

Note: starknet devnet already supports this, we need to pass the host and port flags to it.

**Comment by martriay** [comment]
Thanks for raising this! I'm on macOS but haven't stumbled upon this before. Would you be interested in opening a PR adding the feature @kanishkatn?

**Comment by kanishkatn** [comment]
@martriay Yes, would love to!

**Comment by milancermak** [comment]
Just FYI, there was a [post on Reddit](https://old.reddit.com/r/webdev/comments/qg8yt9/apple_took_over_port_5000_in_the_latest_macos/) about it some time ago. Seems the port squatting can be disabled via System preferences.

**Comment by Yijia-Chen** [comment]
Second this issue. #46 seems to have a good solution already; can someone please merge?

**Comment by martriay** [comment]
@Yijia-Chen hey there, bear in mind that merging it doesn't automatically makes it available since we'd have to also release a new version of nile. Until we release it, I suggest you clone the PR (or `main` when merged) and install it locally to use it now.

**Comment by Yijia-Chen** [comment]
I installed the newest commit including #46 using `python -m pip install .` in the project directory, and `nile node` now has the flag `--port` which works on 5001. However, `nile deploy contract --alias contract_name` still has no `--port` option, and when I run it after `nile node`, it gives me the error that port 5000 is occupied. Am I doing something wrong here? Does the local `nile deploy` also use port 5000?

The detailed error message is as follows: `subprocess.CalledProcessError: Command '['starknet', 'deploy', '--contract', 'artifacts/contract.json', '--gateway_url=http://localhost:5000/']' returned non-zero exit status 1.` I am on macOS Monterey Version 12.0.1.

**Comment by ftupas** [comment]
Hi @Yijia-Chen , normally when you run `nile node --port 5001` you'll have a `node.json` file with the corresponding gateway URL. No need to add the port when executing `nile deploy` as it will target whatever is saved in this file. However you do need to run it in the same directory when you did `nile node`, could you try again and see if it works on your end?

**Comment by Yijia-Chen** [comment]
Okay now it works! I wasn't running them in the same directory. Thanks!

**Comment by martriay** [comment]
I'm closing this issue since the feature is already in place.
