### ISSUE TITLE
Does it support deploying contract with arguments in the latest version? And then, how to do it?

### ISSUE THREAD

**Issue by Alpha2J** [OpenZeppelin/nile#354]

**Comment by martriay** [comment]
Yes. See https://docs.openzeppelin.com/nile/0.14.0/cli#deploy.

**Comment by Alpha2J** [comment]
Hello👏! I need to reopen this issue. According to the documentation, I tried to deploy my contract with the command `nile deploy ACCOUNT_1 MyToken --alias mytoken_abc --network goerli mytoken_n mytoken_s 0x0468b7AdAE55BE128D1e10D13075A0FFF7e1941014F1C0aC780a35D51658965E`. However, I encountered an error as shown in pic1. Additionally, I have included the constructor of my contract in pic2. Could you please check if there is any issue with my usage? I am new to Cairo and not very familiar with it.

![image](https://github.com/OpenZeppelin/nile/assets/17811469/9779de2d-154d-4afa-9dcb-4e5d637d644a)
![image](https://github.com/OpenZeppelin/nile/assets/17811469/b2d26c53-a5d6-4800-8839-86e82af58242)

**Comment by Alpha2J** [comment]
Before using the nile deploy command, I think it might be necessary to convert the string 'mytoken_n' to an integer type. However, I'm unsure about the exact method to do so and haven't been able to find any helpful documentation😞

**Comment by martriay** [comment]
Short strings should be automatically converted, see: https://docs.openzeppelin.com/nile/0.14.0/strings#nile_integration

Alternatively you can use the `str_to_felt` utility.

**Comment by Alpha2J** [comment]
but it doesn't automatically converted:
![image](https://github.com/OpenZeppelin/nile/assets/17811469/4b98b4b4-2370-416e-93c6-7ef9a789f797)

**Comment by martriay** [comment]
what version are you using?

**Comment by Alpha2J** [comment]
0.14.0
![image](https://github.com/OpenZeppelin/nile/assets/17811469/97646955-d676-42a3-a565-9728e83479ba)

and here is the stack trace:
![image](https://github.com/OpenZeppelin/nile/assets/17811469/099e1f41-89ca-47f3-9f4b-b854bfad1798)

**Comment by andrew-fleming** [comment]
Hey @Alpha2J! My apologies, string arguments are unfortunately not supported in the latest release. Since we're no longer maintaining Nile, here's a script tailored to your project to help you deploy:

```
#scripts/my_token.py

from nile.utils import *

ALIAS = "mytoken_abc"
decimals = 18

async def run(nre):
    accounts = await nre.get_accounts()
    account = accounts[0]

    name = str_to_felt("mytoken_n")
    symbol = str_to_felt("mytoken_s")
    admin = 0x0468b7AdAE55BE128D1e10D13075A0FFF7e1941014F1C0aC780a35D51658965E

    arguments = [
        name,
        symbol,
        admin
    ]

    tx = await account.deploy_contract(
        "MyToken",
        salt=0,
        unique=0,
        calldata=arguments,
        alias=ALIAS
    )
    out = await tx.execute()
    print("MyToken deployed at", hex(out[1]))

    supply = await nre.call(ALIAS, "totalSupply")
    print("total supply:", from_decimals(supply))

    name = await nre.call(ALIAS, "name")
    print("token name:", int_to_str(name))

    symbol = await nre.call(ALIAS, "symbol")
    print("token symbol:", int_to_str(symbol))

def from_decimals(x):
    split_str = x.split()
    y = from_uint([int(item, 16) for item in split_str])
    return y / (10 ** decimals)

def to_decimals(x):
    return x * (10 ** decimals)

def from_hex(x):
    return int(x, 16)

def int_to_str(x):
    return felt_to_str(x)
```

Run this with `nile run scripts/my_token.py`. I hope this helps :)
