### ISSUE TITLE
Report compile errors better

### ISSUE THREAD

**Issue by milancermak** [OpenZeppelin/nile#37]
Hey,

I'd like to propose a change, but this might be a nitpick so feel free to ignore.

What do you think about improving the UX by showing a different failure emoji rather than the green thick mark when `nile compile` is done but the contract compilation fails? 

So instead of this:

```
nile compile contracts/contract.cairo
🔨 Compiling contracts/contract.cairo
contracts/contract.cairo:19:5: Expected exactly 0 expressions, got 1.
    return (0)
    ^********^
✅ Done
```

we could have 
```
nile compile contracts/contract.cairo
🔨 Compiling contracts/contract.cairo
contracts/contract.cairo:19:5: Expected exactly 0 expressions, got 1.
    return (0)
    ^********^
🛑 Compilation failed with 1 error
```

It's easier to spot that something actually failed (red vs. green). Would be also useful for a project with a lot of contracts, where the compilation failure might scroll off screen.

I also think if the compilation fails, `nile compile` should [exit with a non zero value](https://bash.cyberciti.biz/guide/The_exit_status_of_a_command) so that it can be used in scripting or CI workflows or in similar context.

I'm happy to send a PR if you believe doing this is worthwhile.

**Comment by martriay** [comment]
Great observation. Please do, that would be awesome!
