### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by milancermak** [OpenZeppelin/nile#44]
How should a nile project be tested?

There's a native `nile test` command (currently undocumented, see #7), which if I understand correctly, expects tests to be written in Cairo. Then there's also the `test` command in the Makefile that's created on `nile init` which runs `pytest tests/`.

What's the idea behind the first approach? Is it used anywhere? 

Is it possible to have just one approach? Or combine the `nile test` command to run both the `.test.cairo` tests and also the ones in `tests/` dir via pytest? Or maybe the `test` command can be removed altogether?

**Comment by fracek** [comment]
In my opinion, at the moment, the best approach is to test using Python. I wrote the `nile test` command to start thinking how, in the future, we can implement a full blown testing framework like dapptools. Before we can implement that, Cairo needs to add `CREATE` or similar. I agree we can remove the command for the time being until Cairo catches up, but I also want to hear @martriay's opinion.

**Comment by martriay** [comment]
Agree on removing the experimental Cairo testing feature in favor of `pytest`. I don't recall if discussion happened over Discord or another github issue, but if this feature comes to be then I'd add it as a flag to `nile test` (e.g. `--cairo` or something).

**Comment by milancermak** [comment]
FWIW I also test using python and tbh I'm not missing anything so far. pytest is such an excellent testing library :)

I have to admit that a dapptools-like testing approach would be cool as well.
