### ISSUE TITLE
Debug contracts with Nile

### ISSUE THREAD

**Issue by fracek** [OpenZeppelin/nile#50]
It would be nice to debug contracts. I wrote a [Cairo debugger](https://github.com/fracek/cairo-dap) that uses the debugger adapter protocol to communicate with VS Code, Emacs, and Vim. The package doesn't work with recent versions of Cairo or StarkNet (that was before StarkNet was announced).

How should the debugger be started? I was thinking it makes sense to pass the contract, a method, and its arguments.

**Comment by martriay** [comment]
I think that interface makes sense for v0.1 but eventually it could be more interactive like traversing available methods and executing them, maybe sequentially to see how state changes after chaining a few calls. In the future this could even work with [a repl](https://github.com/ankitchiplunkar/cairo-jupyter).
