### ISSUE TITLE
Support Nile plugins

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/nile#53]
Add a plugin system to extend Nile's functionality

**Comment by fracek** [comment]
What do you envision for plugins to do? Should they extend the NRE or something else?

The good news is that Python has entry-points, which are basically a system-wide registry of Python classes that can be used to load plugins at runtime.

**Comment by martriay** [comment]
Amazing, how does entrypoints look like?

Yes, I was thinking of:

* Injecting functionality/objects into NRE
* Maybe also adapting existing modules so they can be hooked (e.g. a plugin that hooks into `nile.compile` to do something before/after)

**Comment by alcuadrado** [comment]
> * Injecting functionality/objects into NRE

This can easily prevent you from adding types in the future. Be careful about that design pattern. Take a look at [this old example I made a few years ago](https://github.com/alcuadrado/ts-plugin-system).

> * Maybe also adapting existing modules so they can be hooked (e.g. a plugin that hooks into `nile.compile` to do something before/after)

The main thing you need to decide here is how much flexibility you are willing to give to the users, and how much will your system know about what's going to happen before actually executing a command or task. This is a huge 2-dimensional spectrum. I would try to find examples of projects, understand how they fit this spectrum, and then decide where you want Nile to be.

**Comment by fracek** [comment]
The idea with entry points is that nile would define the interfaces that plugins need to implement and what type of plugin they are (the key in the class/object registry). Plugins then need to update their `setup.cfg` file to register themselves with the registry. When users install a plugin through pip, the plugin is automatically registered. Nile loads the plugin at runtime by looking up the classes registered under a given key.

With an example:

 * Nile defines a `before_compile` entry-point of functions with signature `before_compile(contract):`
 * Plugin developers create a standard Python project and register their functions under the `before_compile` entry-point
 * Nile (at runtime) can inspect all the entry-points registered under the `before_compile` key and call all of them (IMHO bad) or the one specified by the user (better).

**Comment by martriay** [comment]
> Notice that unlike other languages (like typescript), in Python the entry-points are global to the Python installation and so users that don't have per-project virtual environments might have different plugins installed. Most Python apps have users specify which plugins to use to avoid issues with users.

This sounds pretty cool. Can you point me to an example, or maybe draft one?

**Comment by fracek** [comment]
[I created a simple example here](https://github.com/fracek/nile/commit/b250500e263ab5a4faa920bc223a8754cf98a676). Notice that the callbacks will be defined in external projects.

As I mentioned in the comments, the user should explicitly decide which plugins to run to avoid packages being loaded without user knowing about it.
