### ISSUE TITLE
Support for cairo path cmdline arg for nile compile

### ISSUE THREAD

**Issue by milancermak** [OpenZeppelin/nile#72]
I'm running into this need quite often - I would like to pass additional `--cairo_path` directories  to the `nile compile` command. I know I can use `CAIRO_PATH` env var, but there's benefits of having it as a cmdline arg as well.

Would it be of interest to anyone else? If so, I can submit a PR.

**Comment by martriay** [comment]
sounds good to me

**Comment by martriay** [comment]
@comc yes it should
