### ISSUE TITLE
Get accounts

### ISSUE THREAD

**Issue by martriay** [OpenZeppelin/nile#87]
Add functionality to manage/retrieve available accounts on Nile, to use them programmatically.

**Comment by ponderingdemocritus** [comment]
We have created a CLI for the Realms game and have run into one small limitation.

All accounts deployed live within the goerli.deployments.txt file. 

This presents a problem when we wish for users to deploy an account but have it gitignored. Currently, we just ask users to delete the account from the file if they wish to contribute 

**Potential Solution:** 
Save the account information in a different file and let the developer choose to gitignore if they wish.
