### ISSUE TITLE
Error when launching nile node

### ISSUE THREAD

**Issue by yogh333** [OpenZeppelin/nile#93]
After installing nile environment, I have error when trying to launch `nile node`.
The following error is displayed:
`KeyError: 'WERKZEUG_SERVER_FD'`

**Comment by yogh333** [comment]
Ok linked with issue #92 , workarounded by downgrading werkzeug from 2.1.0 down to 2.0.0

**Comment by davidism** [comment]
See https://github.com/OpenZeppelin/nile/pull/86#issuecomment-1086101414
